services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_MULTIPLE_DATABASES: airflow,bookops
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/multiple_postgres.sh:/docker-entrypoint-initdb.d/multiple-databases.sh

  airflow:
    image: apache/airflow:3.2.1-python3.14
    container_name: airflow
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg://airflow:airflow@postgres:5432/airflow
      AIRFLOW_CONN_BOOKSHOP_POSTGRES: postgresql://airflow:airflow@postgres:5432/bookops
      AIRFLOW__API_AUTH__JWT_SECRET: bookshop-workshop-jwt-secret
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
      AIRFLOW_UID: "50000"
      PYTHONPATH: /opt/airflow
      AIRFLOW_HOME: /opt/airflow
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: airflow
      _PIP_ADDITIONAL_REQUIREMENTS: apache-airflow-providers-postgres==6.3.0 httpx==0.28.1 psycopg==3.2.9
    command: >
      bash -lc "
      export AIRFLOW_HOME=/opt/airflow &&
      airflow db migrate &&
      airflow standalone
      "
    ports:
      - "${AIRFLOW_PORT:-8080}:8080"
    volumes:
      - ./:/opt/airflow

  analytics:
    build: ./analytics-app
    depends_on:
      - postgres
    environment:
      BOOKOPS_DB_URL: postgresql://airflow:airflow@postgres:5432/bookops
    ports:
      - "8501:8501"
    volumes:
      - ./analytics-app:/app

volumes:
  postgres_data:
